services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        restart: always
    managingconfigurationnetcore:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - USER_SECRETS_ID=cf22710a-baf0-45a1-8890-18c3b00f12a6
        ports:
        - "80"
        volumes:
        - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/cf22710a-baf0-45a1-8890-18c3b00f12a6
        - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/cf22710a-baf0-45a1-8890-18c3b00f12a6