name: Publish Backend
on:
    push:
        branches:
            - prod
jobs:
    release:
        concurrency:
            group: ${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
        - name: executing remote ssh commands using password test
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: cd /home/website/word-whisper && ecbo hello world > hello.txt && git checkout prod && git pull && bash start.sh
