name: .NET Core CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: kmturhan/word-whisper

    - name: Setup .NET Core
      uses: kmturhan/word-whisper
      with:
        dotnet-version: 7.x

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ./publish
      working-directory: WordWhisper.Web

    - name: Deploy to GitHub Pages
      uses: kmturhan/word-whisper
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
